version: '3'
services:

  migrate-sample-db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: migrate-sample-db
    restart: always
    ports:
      - "13306:3306"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root